name: firebase_analytics_monitor
description: A command-line tool to monitor Firebase Analytics events from logcat.
version: 1.0.1
repository: https://github.com/mzamagias/firebase_analytics_monitor

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.5.0
  cli_completion: ">=0.4.0 <0.6.0"
  equatable: ^2.0.5
  get_it: ^7.6.7
  injectable: ^2.3.5
  isar: ^3.1.0+1
  mason_logger: ^0.2.11
  path: ^1.8.3
  process: ^5.0.2
  pub_updater: ^0.4.0

dev_dependencies:
  build_runner: ^2.4.9
  build_verify: ^3.1.0
  injectable_generator: ^2.1.6
  isar_generator: ^3.1.0+1
  lints: ^3.0.0
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0

executables:
  famon:
